#include "Skylighting.h"

#include "Features/IBL.h"
#include "Features/TexGen.h"
#include "I18n/I18n.h"
#include "ShaderCache.h"
#include "State.h"
#include "Utils/D3D.h"

#define I18N_KEY_PREFIX "feature.skylighting."

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT(
	Skylighting::Settings,
	MaxZenith,
	MinDiffuseVisibility,
	MinSpecularVisibility,
	SkyInfluence,
	EnvInfluence)

void Skylighting::LoadSettings(json& o_json)
{
	settings = o_json;
}

void Skylighting::SaveSettings(json& o_json)
{
	o_json = settings;
}

void Skylighting::RestoreDefaultSettings()
{
	settings = {};
}

void Skylighting::ResetSkylighting()
{
	auto context = globals::d3d::context;
	UINT clr[1] = { 0 };
	context->ClearUnorderedAccessViewUint(texAccumFramesArray->uav.get(), clr);
	queuedResetSkylighting = false;
}

void Skylighting::DrawSettings()
{
	if (ImGui::Button("Reload Shaders"))
		ClearShaderCache();

	ImGui::SliderFloat("Diffuse Min Visibility", &settings.MinDiffuseVisibility, 0.01f, 1.f, "%.2f");
	ImGui::SliderFloat("Specular Min Visibility", &settings.MinSpecularVisibility, 0.01f, 1.f, "%.2f");

	ImGui::SliderFloat("Sky Influence", &settings.SkyInfluence, 0.01f, 5.0f);
	ImGui::SliderFloat("Environment Influence", &settings.EnvInfluence, 0.01f, 5.0f);

	ImGui::Checkbox("Terrain Lighting Map", &updateTerrainLighting);
	ImGui::Checkbox("Sparse Probe Map", &runSparse);

	static float debugRescale = 1.0f;
	ImGui::SliderFloat("View Resize", &debugRescale, 0.0f, 10.0f);

	ImGui::BulletText("Relight View");
	if (terrainLightingTex.get())
		BUFFER_VIEWER_NODE_BULLETA(terrainLightingTex->srv.get(), debugRescale);

	ImGui::BulletText("Probe View");
	if (texSparseProbeArray.get())
		BUFFER_VIEWER_NODE_BULLETA(texSparseProbeArray->srv.get(), debugRescale);

	ImGui::Separator();

	ImGui::Checkbox("Enable Lighting", (bool*)&settings.toggleLighting);  //tmp
	ImGui::Checkbox("Enable Trees", (bool*)&settings.toggleTrees);
	ImGui::Checkbox("Enable Grass", (bool*)&settings.toggleGrass);
	ImGui::Checkbox("Enable Deferred", (bool*)&settings.toggleDeferred);
	ImGui::Checkbox("Enable Effect", (bool*)&settings.toggleEffect);

	ImGui::Separator();

	// Only what is currently loaded is reported here; the maps themselves are baked by TexGen.
	ImGui::TextDisabled("Cache maps are generated by the TexGen feature.");

	std::string curr_worldspace = "N/A";
	auto tes = RE::TES::GetSingleton();
	if (tes) {
		auto worldspace = tes->GetRuntimeData2().worldSpace;
		if (worldspace) {
			curr_worldspace = worldspace->GetFormEditorID();
		}
	}
	ImGui::Text(fmt::format("Worldspace has cache: {}", worldSpaceCachedMapList.contains(curr_worldspace)).c_str());
	ImGui::Text("Cache is loaded: %s", (cacheWorldspaceID == curr_worldspace) ? "true" : "false");

	auto& texGen = globals::features::texGen;

	const auto& heightRange = texGen.GetHeightAtlasRange();
	if (heightRange.valid)
		ImGui::BulletText("Height atlas cells %d,%d to %d,%d", heightRange.minCell.x, heightRange.minCell.y, heightRange.maxCell.x, heightRange.maxCell.y);

	const auto& bentNormalRange = texGen.GetBentNormalAtlasRange();
	if (bentNormalRange.valid)
		ImGui::BulletText("BN atlas cells %d,%d to %d,%d", bentNormalRange.minCell.x, bentNormalRange.minCell.y, bentNormalRange.maxCell.x, bentNormalRange.maxCell.y);

	if (BNTileSRV)
		ImGui::BulletText("Streamed BN tile: cell %d, %d (%.0f, %.0f to %.0f, %.0f)",
			bnTileOriginCell.x, bnTileOriginCell.y,
			bnTileWorldBounds.x, bnTileWorldBounds.y, bnTileWorldBounds.z, bnTileWorldBounds.w);
	else if (bnTileOriginValid)
		ImGui::BulletText("Streamed BN tile: none for cell %d, %d", bnTileOriginCell.x, bnTileOriginCell.y);

	ImGui::Separator();

	if (ImGui::Button("Rebuild Skylighting"))
		ResetSkylighting();

	if (auto _tt = Util::HoverTooltipWrapper())
		ImGui::Text("Changes below require rebuilding, a loading screen, or moving away from the current location to apply.");

	ImGui::SliderAngle("Max Zenith Angle", &settings.MaxZenith, 0, 90);
	if (auto _tt = Util::HoverTooltipWrapper())
		ImGui::Text("Smaller angles creates more focused top-down shadow.");
}

void Skylighting::SetupResources()
{
	auto renderer = globals::game::renderer;
	auto device = globals::d3d::device;

	{
		auto& precipitationOcclusion = renderer->GetDepthStencilData().depthStencils[RE::RENDER_TARGETS_DEPTHSTENCIL::kPRECIPITATION_OCCLUSION_MAP];

		D3D11_TEXTURE2D_DESC texDesc{};
		D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc = {};
		D3D11_DEPTH_STENCIL_VIEW_DESC dsvDesc = {};

		precipitationOcclusion.texture->GetDesc(&texDesc);
		precipitationOcclusion.depthSRV->GetDesc(&srvDesc);
		precipitationOcclusion.views[0]->GetDesc(&dsvDesc);

		texOcclusion = new Texture2D(texDesc);
		texOcclusion->CreateSRV(srvDesc);
		texOcclusion->CreateDSV(dsvDesc);
	}

	{
		D3D11_TEXTURE3D_DESC texDesc{
			.Width = probeArrayDims[0],
			.Height = probeArrayDims[1],
			.Depth = probeArrayDims[2],
			.MipLevels = 1,
			.Format = DXGI_FORMAT_R16G16B16A16_FLOAT,
			.Usage = D3D11_USAGE_DEFAULT,
			.BindFlags = D3D11_BIND_SHADER_RESOURCE | D3D11_BIND_UNORDERED_ACCESS,
			.CPUAccessFlags = 0,
			.MiscFlags = 0
		};
		D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc = {
			.Format = texDesc.Format,
			.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE3D,
			.Texture3D = {
				.MostDetailedMip = 0,
				.MipLevels = texDesc.MipLevels }
		};
		D3D11_UNORDERED_ACCESS_VIEW_DESC uavDesc = {
			.Format = texDesc.Format,
			.ViewDimension = D3D11_UAV_DIMENSION_TEXTURE3D,
			.Texture3D = {
				.MipSlice = 0,
				.FirstWSlice = 0,
				.WSize = texDesc.Depth }
		};

		texProbeArray = new Texture3D(texDesc);
		texProbeArray->CreateSRV(srvDesc);
		texProbeArray->CreateUAV(uavDesc);

		texDesc.Format = srvDesc.Format = uavDesc.Format = DXGI_FORMAT_R8_UINT;

		texAccumFramesArray = new Texture3D(texDesc);
		texAccumFramesArray->CreateSRV(srvDesc);
		texAccumFramesArray->CreateUAV(uavDesc);
	}

	{
		CD3D11_TEXTURE2D_DESC texDesc(DXGI_FORMAT_R32G32B32A32_FLOAT, sparseGridSize.x, sparseGridSize.y, 3, 1, D3D11_BIND_UNORDERED_ACCESS | D3D11_BIND_SHADER_RESOURCE);
		CD3D11_SHADER_RESOURCE_VIEW_DESC srvDesc(D3D11_SRV_DIMENSION_TEXTURE2DARRAY, texDesc.Format, 0, 1, 0, 3);
		CD3D11_UNORDERED_ACCESS_VIEW_DESC uavDesc(D3D11_UAV_DIMENSION_TEXTURE2DARRAY, texDesc.Format, 0, 0, 3);

		texSparseProbeArray = eastl::make_unique<Texture2D>(texDesc);
		texSparseProbeArray->CreateSRV(srvDesc);
		texSparseProbeArray->CreateUAV(uavDesc);
	}

	{
		CD3D11_TEXTURE2D_DESC texDesc(DXGI_FORMAT_R32G32B32A32_FLOAT, terrainMapSize.x, terrainMapSize.y, 1, 1, D3D11_BIND_UNORDERED_ACCESS | D3D11_BIND_SHADER_RESOURCE);
		CD3D11_SHADER_RESOURCE_VIEW_DESC srvDesc(D3D11_SRV_DIMENSION_TEXTURE2D, texDesc.Format, 0, 1, 0, 1);
		CD3D11_UNORDERED_ACCESS_VIEW_DESC uavDesc(D3D11_UAV_DIMENSION_TEXTURE2D, texDesc.Format, 0, 0, 1);

		terrainLightingTex = eastl::make_unique<Texture2D>(texDesc);
		terrainLightingTex->CreateSRV(srvDesc);
		terrainLightingTex->CreateUAV(uavDesc);
	}

	{
		D3D11_SAMPLER_DESC samplerDesc = {};
		samplerDesc.Filter = D3D11_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR;  // Use comparison filtering
		samplerDesc.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;               // Address mode (Clamp for shadow maps)
		samplerDesc.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
		samplerDesc.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
		samplerDesc.ComparisonFunc = D3D11_COMPARISON_LESS_EQUAL;  // Comparison function
		samplerDesc.MinLOD = 0;
		samplerDesc.MaxLOD = D3D11_FLOAT32_MAX;
		DX::ThrowIfFailed(device->CreateSamplerState(&samplerDesc, comparisonSampler.put()));
	}

	GetCachedWorldspaces();

	CompileComputeShaders();

	// The height cache staging tile is created on demand, since its size depends on the settings.
}

void Skylighting::GetCachedWorldspaces()
{
	std::error_code ec;
	for (const auto& entry : std::filesystem::directory_iterator(TexGen::cachePath, ec)) {
		auto& path = entry.path();
		if (path.extension() == ".dds") {
			auto name = path.stem().string();
			if (name.contains('.'))  // height tiles are "<Worldspace>_H<size>.<cells>.<x>.<y>", not worldspace maps
				continue;
			logger::debug("[Skylighting] Found cache: {}", name);
			if (worldSpaceCachedMapList.contains(name))
				logger::warn("[Skylighting] Error: {} has multiple maps with same name", name);
			worldSpaceCachedMapList.insert(name);
		}
	}
}

bool Skylighting::LoadCacheMap(const std::filesystem::path& a_path, ID3D11ShaderResourceView** a_srv)
{
	if (*a_srv) {
		(*a_srv)->Release();
		*a_srv = nullptr;
	}

	auto result = DirectX::CreateDDSTextureFromFile(globals::d3d::device, globals::d3d::context, a_path.c_str(), nullptr, a_srv);
	if (FAILED(result)) {
		*a_srv = nullptr;
		return false;
	}

	return true;
}

bool Skylighting::LoadWorldspaceCache()
{
	auto& texGen = globals::features::texGen;

	auto newWorldspaceID = TexGen::GetCurrentWorldspaceID();
	if (newWorldspaceID.empty())
		return false;

	if (cacheWorldspaceID == newWorldspaceID)
		return true;

	// The streamed tile belongs to the old worldspace
	ReleaseBentNormalTileStream();

	logger::info("[Skylighting] Loading cached texture maps...");

	// The height atlas has to come first: every generator reads it, and generating against a
	// null height map would write out empty maps.
	{
		texGen.SetHeightMapSRV(nullptr);  // TexGen holds a non-owning view of the texture released below

		std::filesystem::path path;
		if (texGen.ResolveHeightAtlas(newWorldspaceID, path)) {
			if (!LoadCacheMap(path, &HMapSRV))
				logger::error("[Skylighting] Failed to load height atlas {}", path.string());
		} else {
			logger::error("[Skylighting] No height atlas found for {}", newWorldspaceID);
		}

		texGen.SetHeightMapSRV(HMapSRV);
	}

	{
		auto path = TexGen::cachePath / (newWorldspaceID + "_A.dds");
		if (!LoadCacheMap(path, &AMapSRV) && texGen.BuildLODAtlas(path, ""))
			LoadCacheMap(path, &AMapSRV);
	}

	{
		auto path = TexGen::cachePath / (newWorldspaceID + "_N.dds");
		if (!LoadCacheMap(path, &NMapSRV) && texGen.GenerateNormalMap())
			LoadCacheMap(path, &NMapSRV);
	}

	{
		std::filesystem::path path;
		if (texGen.ResolveBentNormalAtlas(newWorldspaceID, path)) {
			// A map that exists but will not load is never regenerated over: it is far more likely
			// to be too large for D3D11 than to be corrupt, and overwriting it would throw away a
			// bake that took hours.
			if (!LoadCacheMap(path, &BNMapSRV))
				logger::error("[Skylighting] {} exists but failed to load; leaving it untouched", path.string());
		} else if (texGen.GenerateBentNormalMap()) {  // no tiles to stitch, fall back to the full map pass
			if (texGen.ResolveBentNormalAtlas(newWorldspaceID, path))
				LoadCacheMap(path, &BNMapSRV);
		}
	}

	// A single pass writes all six occlusion maps, so any one of them missing regenerates the set.
	{
		static constexpr std::array<const char*, 6> occlusionTags = { "_CO", "_CO2", "_DO", "_DO2", "_DOB", "_DO2B" };
		ID3D11ShaderResourceView** occlusionSRVs[6] = { &COMapSRV, &CO2MapSRV, &DOMapSRV, &DO2MapSRV, &DOMapSRVB, &DO2MapSRVB };

		bool anyMissing = false;
		for (size_t i = 0; i < occlusionTags.size(); ++i)
			anyMissing = !LoadCacheMap(TexGen::cachePath / (newWorldspaceID + occlusionTags[i] + ".dds"), occlusionSRVs[i]) || anyMissing;

		if (anyMissing && texGen.GenerateCardinalOcclusionMap())
			for (size_t i = 0; i < occlusionTags.size(); ++i)
				LoadCacheMap(TexGen::cachePath / (newWorldspaceID + occlusionTags[i] + ".dds"), occlusionSRVs[i]);
	}

	// Recorded last: a generator above asks for a reload by clearing this, and setting it before the
	// load finished would leave that request satisfied by a load that never saw the new files.
	cacheWorldspaceID = newWorldspaceID;

	return true;
}

void Skylighting::ClearShaderCache()
{
	static const std::vector<winrt::com_ptr<ID3D11ComputeShader>*> shaderPtrs = {
		&probeUpdateCompute,
		&updateSparseGridCS,
		&terrainRelightCS,
	};

	for (auto shader : shaderPtrs)
		shader = nullptr;

	CompileComputeShaders();
}

void Skylighting::CompileComputeShaders()
{
	struct ShaderCompileInfo
	{
		winrt::com_ptr<ID3D11ComputeShader>* programPtr;
		std::string_view filename;
		std::vector<std::pair<const char*, const char*>> defines;
	};

	std::vector<ShaderCompileInfo>
		shaderInfos = {
			{ &probeUpdateCompute, "UpdateProbesCS.hlsl", { { "DENSE_PROBE_GRID", "" } } },
			{ &updateSparseGridCS, "UpdateProbesCS.hlsl", { { "SPARSE_PROBE_GRID", "" } } },
			{ &terrainRelightCS, "UpdateProbesCS.hlsl", { { "TERRAIN_RELIGHT", "" } } },
		};

	for (auto& info : shaderInfos) {
		auto path = std::filesystem::path("Data\\Shaders\\Skylighting") / info.filename;
		if (auto rawPtr = reinterpret_cast<ID3D11ComputeShader*>(Util::CompileShader(path.c_str(), info.defines, "cs_5_0")))
			info.programPtr->attach(rawPtr);
	}
}

void Skylighting::UpdateDenseProbeGrid()
{
	auto context = globals::d3d::context;

	if (globals::state->frameAnnotations)
		globals::state->BeginPerfEvent("Skylighting - Update Dense Probes");

	TracyD3D11Zone(globals::state->tracyCtx, "Skylighting - Update Dense Probes");

	std::array<ID3D11ShaderResourceView*, 1> srvs = { texOcclusion->srv.get() };
	std::array<ID3D11UnorderedAccessView*, 2> uavs = { texProbeArray->uav.get(), texAccumFramesArray->uav.get() };
	std::array<ID3D11SamplerState*, 1> samplers = { comparisonSampler.get() };

	// Update probe array
	{
		context->CSSetSamplers(0, (uint)samplers.size(), samplers.data());
		context->CSSetShaderResources(0, (uint)srvs.size(), srvs.data());
		context->CSSetUnorderedAccessViews(0, (uint)uavs.size(), uavs.data(), nullptr);
		context->CSSetShader(probeUpdateCompute.get(), nullptr, 0);
		context->Dispatch((probeArrayDims[0] + 7u) >> 3, (probeArrayDims[1] + 7u) >> 3, probeArrayDims[2]);
	}

	if (globals::state->frameAnnotations)
		globals::state->EndPerfEvent();
}

void Skylighting::UpdateTerrainLighting()
{
	auto context = globals::d3d::context;

	//GenerateNormalStepMap();

	if (globals::state->frameAnnotations)
		globals::state->BeginPerfEvent("Skylighting - Terrain Lighting");

	TracyD3D11Zone(state->tracyCtx, "Skylighting - Terrain Lighting");

	auto uav = terrainLightingTex->uav.get();
	context->CSSetShader(terrainRelightCS.get(), nullptr, 0);
	context->CSSetUnorderedAccessViews(0, 1, &uav, nullptr);

	ID3D11SamplerState* sampArray[3] = { globals::deferred->linearSampler, globals::features::physicalSky.sampNoise.get(), globals::features::physicalSky.sampSv.get() };
	context->CSSetSamplers(0, 1, sampArray);

	ID3D11ShaderResourceView* srvs[] = {
		globals::features::physicalSky.texSvLut->srv.get(),
		HMapSRV,  //globals::features::terrainShadows.texHeightMap->srv.get(),
		BNMapSRV,
		COMapSRV,
		CO2MapSRV,
		AMapSRV,
		NMapSRV,
		globals::features::physicalSky.texTrLut->srv.get(),
	};

	context->CSSetShaderResources(0, ARRAYSIZE(srvs), srvs);

	context->Dispatch((terrainMapSize.x + 7) / 8, (terrainMapSize.y + 7) / 8, 1);

	ID3D11UnorderedAccessView* nullUAVs[2] = { nullptr, nullptr };
	context->CSSetUnorderedAccessViews(0, 1, nullUAVs, nullptr);

	if (globals::state->frameAnnotations)
		globals::state->EndPerfEvent();
}

void Skylighting::UpdateSparseProbeGrid()
{
	auto context = globals::d3d::context;

	if (globals::state->frameAnnotations)
		globals::state->BeginPerfEvent("Skylighting - Update Sparse Probes");

	TracyD3D11Zone(state->tracyCtx, "Skylighting - Update Sparse Probes");

	auto uav = texSparseProbeArray->uav.get();
	context->CSSetShader(updateSparseGridCS.get(), nullptr, 0);
	context->CSSetUnorderedAccessViews(0, 1, &uav, nullptr);

	ID3D11SamplerState* sampArray[3] = { globals::deferred->linearSampler, globals::features::physicalSky.sampNoise.get(), globals::features::physicalSky.sampSv.get() };
	context->CSSetSamplers(0, 3, sampArray);

	ID3D11Buffer* buffer[2] = { globals::features::physicalSky.cloudBuffer->CB(), globals::features::physicalSky.cloudDebugBuffer->CB() };
	context->CSSetConstantBuffers(0, 2, buffer);

	auto& physSky = globals::features::physicalSky;
	//auto& depthTexture = globals::game::renderer->GetDepthStencilData().depthStencils[RE::RENDER_TARGETS_DEPTHSTENCIL::kMAIN];

	ID3D11ShaderResourceView* srvs[] = {
		HMapSRV,
		physSky.texSvLut->srv.get(),

		AMapSRV,
		BNMapSRV,
		DOMapSRV,
		DO2MapSRV,
		DOMapSRVB,
		DO2MapSRVB,

		physSky.cloudBaseSRV.get(),  //t8

		NMapSRV,
	};

	context->CSSetShaderResources(0, ARRAYSIZE(srvs), srvs);

	ID3D11ShaderResourceView* skyIBLSRV = globals::features::ibl.skyIBLTexture ? globals::features::ibl.skyIBLTexture->srv.get() : nullptr;
	context->CSSetShaderResources(77, 1, &skyIBLSRV);

	context->Dispatch((sparseGridSize.x + 7) / 8, (sparseGridSize.y + 7) / 8, 1);

	ID3D11UnorderedAccessView* nullUAVs[1] = { nullptr };
	context->CSSetUnorderedAccessViews(0, 1, nullUAVs, nullptr);

	skyIBLSRV = nullptr;
	context->CSSetShaderResources(77, 1, &skyIBLSRV);

	if (globals::state->frameAnnotations)
		globals::state->EndPerfEvent();
}

Skylighting::SkylightingCB Skylighting::GetCommonBufferData(bool a_inWorld)
{
	if (!a_inWorld)
		return Skylighting::SkylightingCB{};

	if (globals::state->isMapMenuOpen)
		return Skylighting::SkylightingCB{};

	auto tes = RE::TES::GetSingleton();
	auto worldspace = tes ? tes->GetRuntimeData2().worldSpace : nullptr;

	if (!worldspace)
		return Skylighting::SkylightingCB{};

	static float3 prevCellID = { 0, 0, 0 };

	auto eyePosNI = Util::GetEyePosition();
	auto eyePos = float3{ eyePosNI.x, eyePosNI.y, eyePosNI.z };

	float3 cellSize = {
		occlusionDistance / probeArrayDims[0],
		occlusionDistance / probeArrayDims[1],
		occlusionDistance * .5f / probeArrayDims[2]
	};
	auto cellID = eyePos / cellSize;
	cellID = { round(cellID.x), round(cellID.y), round(cellID.z) };
	auto cellOrigin = cellID * cellSize;
	float3 cellIDDiff = prevCellID - cellID;
	prevCellID = cellID;

	float2 gridSpan = worldspace->maximumCoords - worldspace->minimumCoords;
	gridSpan = float2(std::abs(gridSpan.x), std::abs(gridSpan.y));

	auto shadowSceneNode = globals::game::smState->shadowSceneNode[0];
	auto dirLight = skyrim_cast<RE::NiDirectionalLight*>(shadowSceneNode->GetRuntimeData().sunLight->light.get());
	const auto& direction = dirLight->GetWorldDirection();
	float3 lightDir = { -direction.x, -direction.y, -direction.z };
	lightDir.Normalize();

	float4 Basis0;
	float4 Basis1;
	BuildOcclusionBasis(lightDir, Basis0, Basis1, 1.0);

	float3 pos = cellOrigin - eyePos;

	return {
		.OcclusionViewProj = OcclusionTransform,
		.OcclusionDir = OcclusionDir,
		.PosOffset = float4(pos.x, pos.y, pos.z, 1.0),
		.ArrayOrigin = {
			((int)cellID.x - probeArrayDims[0] / 2) % probeArrayDims[0],
			((int)cellID.y - probeArrayDims[1] / 2) % probeArrayDims[1],
			((int)cellID.z - probeArrayDims[2] / 2) % probeArrayDims[2], 0 },
		.ValidMargin = { (int)cellIDDiff.x, (int)cellIDDiff.y, (int)cellIDDiff.z },

		.GridTexSize = sparseGridSize,
		.EnvRadianceTexSize = terrainMapSize,
		.GridBounds = float4(worldspace->minimumCoords.x, worldspace->minimumCoords.y, worldspace->maximumCoords.x, worldspace->maximumCoords.y),
		.InvGridTexSize = 1.0f / float2((float)sparseGridSize.x, (float)sparseGridSize.y),
		.InvEnvRadianceTexSize = 1.0f / float2((float)terrainMapSize.x, (float)terrainMapSize.y),
		.GridMinWorldCorner = worldspace->minimumCoords - float2(eyePos.x, eyePos.y),

		.InvGridSpan = 1.0 / gridSpan,
		.HasCache = worldHasCache,
		.toggleLighting = settings.toggleLighting,
		.toggleTrees = settings.toggleTrees,
		.toggleGrass = settings.toggleGrass,
		.toggleDeferred = settings.toggleDeferred,
		.toggleEffect = settings.toggleEffect,

		.MinDiffuseVisibility = settings.MinDiffuseVisibility,
		.MinSpecularVisibility = settings.MinSpecularVisibility,
		.SkyInfluence = settings.SkyInfluence,
		.EnvInfluence = settings.EnvInfluence,
		.Basis0 = Basis0,
		.Basis1 = Basis1,

		.BentNormalTileBounds = bnTileWorldBounds,
		.BentNormalAtlasBounds = globals::features::texGen.GetBentNormalAtlasBounds(),
		.HasBentNormalTile = BNTileSRV != nullptr,
		.HasBentNormalAtlas = BNMapSRV != nullptr,
	};
}

void Skylighting::Prepass()
{
	if (globals::state->isMapMenuOpen)
		return;

	bool interior = true;

	if (auto sky = globals::game::sky)
		interior = sky->mode.get() != RE::Sky::Mode::kFull;

	if (interior)
		return;

	worldHasCache = LoadWorldspaceCache();

	UpdateBentNormalTileStream();

	UpdateDenseProbeGrid();

	if (updateTerrainLighting)
		UpdateTerrainLighting();

	if (runSparse)
		UpdateSparseProbeGrid();

	auto context = globals::d3d::context;
	// t50: dense probes, t51: sparse probes, t52: bent normal atlas, t53: streamed bent normal tile
	ID3D11ShaderResourceView* srvs[4] = { texProbeArray->srv.get(), texSparseProbeArray->srv.get(), BNMapSRV, BNTileSRV };
	context->PSSetShaderResources(50, 4, srvs);
	context->CSSetShaderResources(50, 4, srvs);
}

void Skylighting::PostPostLoad()
{
	logger::info("[SKYLIGHTING] Hooking BSLightingShaderProperty::GetPrecipitationOcclusionMapRenderPassesImp");
	stl::write_vfunc<0x2D, BSLightingShaderProperty_GetPrecipitationOcclusionMapRenderPassesImpl>(RE::VTABLE_BSLightingShaderProperty[0]);
	stl::write_thunk_call<Main_Precipitation_RenderOcclusion>(REL::RelocationID(35560, 36559).address() + REL::Relocate(0x3A1, 0x3A1));

	stl::write_thunk_call<SetViewFrustum>(REL::RelocationID(25643, 26185).address() + REL::Relocate(0x5D9, 0x59D));

	MenuOpenCloseEventHandler::Register();
}

//////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////

RE::BSShaderProperty::RenderPassArray* Skylighting::BSLightingShaderProperty_GetPrecipitationOcclusionMapRenderPassesImpl::thunk(
	RE::BSLightingShaderProperty* property,
	RE::BSGeometry* geometry,
	[[maybe_unused]] uint32_t renderMode,
	[[maybe_unused]] RE::BSGraphics::BSShaderAccumulator* accumulator)
{
	auto& skylighting = globals::features::skylighting;

	auto batch = accumulator->GetRuntimeData().batchRenderer;
	batch->geometryGroups[14]->flags &= ~1;

	using enum RE::BSShaderProperty::EShaderPropertyFlag;
	using enum RE::BSUtilityShader::Flags;

	auto* precipitationOcclusionMapRenderPassList = &property->occlusionPasses;

	precipitationOcclusionMapRenderPassList->Clear();
	if (skylighting.inOcclusion) {
		if (property->flags.any(kSkinned) && property->flags.none(kTreeAnim))
			return precipitationOcclusionMapRenderPassList;
	} else {
		if (property->flags.any(kSkinned))
			return precipitationOcclusionMapRenderPassList;
	}

	if (skylighting.inOcclusion) {
		if (auto userData = geometry->GetUserData()) {
			RE::BSFadeNode* fadeNode = nullptr;

			RE::NiNode* parent = geometry->parent;
			while (parent && !fadeNode) {
				fadeNode = parent->AsFadeNode();
				parent = parent->parent;
			}

			if (fadeNode) {
				if (auto extraData = fadeNode->GetExtraData("BSX")) {
					auto bsxFlags = (RE::BSXFlags*)extraData;
					auto value = static_cast<int32_t>(bsxFlags->value);

					if (value & (static_cast<int32_t>(RE::BSXFlags::Flag::kRagdoll) |
									static_cast<int32_t>(RE::BSXFlags::Flag::kEditorMarker) |
									static_cast<int32_t>(RE::BSXFlags::Flag::kDynamic) |
									static_cast<int32_t>(RE::BSXFlags::Flag::kAddon) |
									static_cast<int32_t>(RE::BSXFlags::Flag::kNeedsTransformUpdate) |
									static_cast<int32_t>(RE::BSXFlags::Flag::kMagicShaderParticles) |
									static_cast<int32_t>(RE::BSXFlags::Flag::kLights) |
									static_cast<int32_t>(RE::BSXFlags::Flag::kBreakable) |
									static_cast<int32_t>(RE::BSXFlags::Flag::kSearchedBreakable))) {
						return precipitationOcclusionMapRenderPassList;
					}
				}
			}
		}
	}

	bool valid = false;

	if (skylighting.inOcclusion) {
		valid = property->flags.any(kZBufferWrite) && property->flags.none(kRefraction, kTempRefraction, kLODLandscape, kEyeReflect, kDecal, kDynamicDecal);
	} else {
		valid = property->flags.any(kZBufferWrite) && property->flags.none(kRefraction, kTempRefraction, kMultiTextureLandscape, kNoLODLandBlend, kLODLandscape, kEyeReflect, kDecal, kDynamicDecal);
	}

	if (valid) {
		if (geometry->worldBound.radius > 32) {
			stl::enumeration<RE::BSUtilityShader::Flags> technique;
			technique.set(RenderDepth);

			if (property->flags.any(kVertexColors)) {
				technique.set(Vc);
			}

			const auto alphaProperty = static_cast<RE::NiAlphaProperty*>(geometry->GetGeometryRuntimeData().alphaProperty.get());
			if (alphaProperty && alphaProperty->GetAlphaTesting()) {
				technique.set(Texture);
				technique.set(AlphaTest);
			}

			if (property->flags.any(kLODObjects, kHDLODObjects)) {
				technique.set(LodObject);
			}

			if (property->flags.any(kTreeAnim)) {
				technique.set(TreeAnim);
			}

			if (property->flags.any(kLODLandscape)) {
				technique.set(LodLandscape);
			}

			precipitationOcclusionMapRenderPassList->EmplacePass(
				globals::game::utilityShader,
				property,
				geometry,
				technique.underlying() + static_cast<uint32_t>(ShaderTechnique::UtilityGeneralStart));
		}
	}

	return precipitationOcclusionMapRenderPassList;
}

void Skylighting::SetViewFrustum::thunk(RE::NiCamera* a_camera, RE::NiFrustum* a_frustum)
{
	auto& skylighting = globals::features::skylighting;

	if (skylighting.inOcclusion) {
		uint corner = skylighting.frameCount % 4;

		float frustumSize = a_frustum->fTop;
		a_frustum->fBottom = (corner == 0 || corner == 1) ? -frustumSize : 0.0f;
		a_frustum->fLeft = (corner == 0 || corner == 2) ? -frustumSize : 0.0f;
		a_frustum->fRight = (corner == 1 || corner == 3) ? frustumSize : 0.0f;
		a_frustum->fTop = (corner == 2 || corner == 3) ? frustumSize : 0.0f;
	}

	func(a_camera, a_frustum);
}

void Skylighting::SetViewFrustumVR::thunk(RE::NiCamera* a_camera, RE::NiFrustum* a_frustum, uint a_eyeIndex)
{
	auto& skylighting = globals::features::skylighting;

	if (skylighting.inOcclusion) {
		uint corner = skylighting.frameCount % 4;

		float frustumSize = a_frustum->fTop;
		a_frustum->fBottom = (corner == 0 || corner == 1) ? -frustumSize : 0.0f;
		a_frustum->fLeft = (corner == 0 || corner == 2) ? -frustumSize : 0.0f;
		a_frustum->fRight = (corner == 1 || corner == 3) ? frustumSize : 0.0f;
		a_frustum->fTop = (corner == 2 || corner == 3) ? frustumSize : 0.0f;
	}

	func(a_camera, a_frustum, a_eyeIndex);
}

void Skylighting::RenderOcclusion()
{
	ZoneScopedS(8);
	auto shaderCache = globals::shaderCache;
	auto state = globals::state;
	auto renderer = globals::game::renderer;
	auto sky = globals::game::sky;

	if (!shaderCache->IsEnabled()) {
		TracyD3D11Zone(globals::state->tracyCtx, "Precipitation Mask");
		state->BeginPerfEvent("Precipitation Mask");
		Main_Precipitation_RenderOcclusion::func();
		state->EndPerfEvent();
		return;
	}

	if (sky) {
		if (!Util::IsInterior()) {
			static bool doPrecip = false;

			auto precip = sky->precip;

			{
				TracyD3D11Zone(globals::state->tracyCtx, "Precipitation Mask");
				state->BeginPerfEvent("Precipitation Mask");

				doPrecip = false;

				auto precipObject = precip->currentPrecip;
				if (!precipObject) {
					precipObject = precip->lastPrecip;
				}
				if (precipObject) {
					precip->SetupMask();
					auto& effect = precipObject->GetGeometryRuntimeData().shaderProperty;
					auto shaderProp = effect.get();
					auto particleShaderProperty = netimmerse_cast<RE::BSParticleShaderProperty*>(shaderProp);
					auto rain = (RE::BSParticleShaderRainEmitter*)(particleShaderProperty->particleEmitter);

					globals::profiler->BeginPass("Skylighting::PrecipMask");
					precip->RenderMask(rain);
					globals::profiler->EndPass();
				}

				state->EndPerfEvent();
			}

			{
				TracyD3D11Zone(globals::state->tracyCtx, "Skylighting Mask");
				state->BeginPerfEvent("Skylighting Mask");

				if (queuedResetSkylighting)
					ResetSkylighting();

				frameCount++;

				auto& precipitation = renderer->GetDepthStencilData().depthStencils[RE::RENDER_TARGETS_DEPTHSTENCIL::kPRECIPITATION_OCCLUSION_MAP];
				RE::BSGraphics::DepthStencilData precipitationCopy = precipitation;

				precipitation.depthSRV = texOcclusion->srv.get();
				precipitation.texture = texOcclusion->resource.get();
				precipitation.views[0] = texOcclusion->dsv.get();

				static float& PrecipitationShaderCubeSize = (*(float*)REL::RelocationID(515451, 401590).address());
				float originalPrecipitationShaderCubeSize = PrecipitationShaderCubeSize;

				static RE::NiPoint3& PrecipitationShaderDirection = (*(RE::NiPoint3*)REL::RelocationID(515509, 401648).address());
				RE::NiPoint3 originalParticleShaderDirection = PrecipitationShaderDirection;

				inOcclusion = true;
				PrecipitationShaderCubeSize = occlusionDistance;

				float originaLastCubeSize = precip->lastCubeSize;
				precip->lastCubeSize = PrecipitationShaderCubeSize;

				float2 vPoint;
				{
					constexpr float rcpRandMax = 1.f / RAND_MAX;
					static int randSeed = std::rand();
					static uint randFrameCount = 0;

					// r2 sequence
					vPoint = float2(randSeed * rcpRandMax) + (float)randFrameCount * float2(0.245122333753f, 0.430159709002f);
					vPoint.x -= static_cast<unsigned long long>(vPoint.x);
					vPoint.y -= static_cast<unsigned long long>(vPoint.y);

					randFrameCount++;
					if (randFrameCount == 1000) {
						randFrameCount = 0;
						randSeed = std::rand();
					}

					// disc transformation
					vPoint.x = sqrt(vPoint.x * sin(settings.MaxZenith));
					vPoint.y *= 6.28318530718f;

					vPoint = { vPoint.x * cos(vPoint.y), vPoint.x * sin(vPoint.y) };
				}

				float3 PrecipitationShaderDirectionF = -float3{ vPoint.x, vPoint.y, sqrt(1 - vPoint.LengthSquared()) };
				PrecipitationShaderDirectionF.Normalize();

				PrecipitationShaderDirection = { PrecipitationShaderDirectionF.x, PrecipitationShaderDirectionF.y, PrecipitationShaderDirectionF.z };

				static REL::Relocation<void(RE::Precipitation*, RE::NiPointer<RE::NiCamera>)> _computeProjection{ REL::RelocationID(25643, 26185) };
				{
					ZoneScopedN("Skylighting - Setup Projection");
					_computeProjection(precip, precip->occlusionData.camera);
					precip->SetupMask();
				}

				BSParticleShaderRainEmitter* rain = new BSParticleShaderRainEmitter;
				{
					TracyD3D11Zone(state->tracyCtx, "Skylighting - Render Height Map");
					globals::profiler->BeginPass("Skylighting::OcclusionMask");
					precip->RenderMask((RE::BSParticleShaderRainEmitter*)rain);
					globals::profiler->EndPass();
				}
				inOcclusion = false;

				OcclusionDir = -float4{ PrecipitationShaderDirectionF.x, PrecipitationShaderDirectionF.y, PrecipitationShaderDirectionF.z, 0 };
				OcclusionTransform = ((RE::BSParticleShaderRainEmitter*)rain)->occlusionProjection;

				delete rain;

				PrecipitationShaderCubeSize = originalPrecipitationShaderCubeSize;
				precip->lastCubeSize = originaLastCubeSize;

				PrecipitationShaderDirection = originalParticleShaderDirection;

				precipitation = precipitationCopy;

				{
					ZoneScopedN("Skylighting - Restore Projection");
					_computeProjection(precip, precip->occlusionData.camera);
				}

				state->EndPerfEvent();
			}
		}
	}
}
void Skylighting::Main_Precipitation_RenderOcclusion::thunk()
{
	// While TexGen bakes the height cache the player is teleported across the worldspace every few
	// frames, so rendering the occlusion mask through that is wasted work. TexGen steps its own
	// bakes from Prepass, so nothing needs pumping from here.
	if (!globals::features::texGen.IsHeightGenRunning())
		globals::features::skylighting.RenderOcclusion();
}

RE::BSEventNotifyControl Skylighting::MenuOpenCloseEventHandler::ProcessEvent(const RE::MenuOpenCloseEvent* a_event, RE::BSTEventSource<RE::MenuOpenCloseEvent>*)
{
	// When entering a new cell through a loadscreen, update every frame until completion
	if (a_event->menuName == RE::LoadingMenu::MENU_NAME) {
		if (!a_event->opening)
			globals::features::skylighting.queuedResetSkylighting = true;
	}

	return RE::BSEventNotifyControl::kContinue;
}

void Skylighting::ReleaseBentNormalTileStream()
{
	if (BNTileSRV) {
		BNTileSRV->Release();
		BNTileSRV = nullptr;
	}

	bnTileOriginValid = false;
	bnTileWorldBounds = float4(0, 0, 0, 0);
}

void Skylighting::UpdateBentNormalTileStream()
{
	auto& texGen = globals::features::texGen;

	// Baking teleports the player across the worldspace, which would thrash the stream.
	if (texGen.IsGenerating())
		return;

	const int cellsPerTile = texGen.GetAtlasTileCells();
	const int tileSize = texGen.GetAtlasTileSize();
	if (cellsPerTile <= 0 || tileSize <= 0 || cacheWorldspaceID.empty())
		return;

	auto player = RE::PlayerCharacter::GetSingleton();
	if (!player)
		return;

	auto playerPos = player->GetPosition();
	const int2 originCell = TexGen::GetTileOriginCell(TexGen::WorldToCell(playerPos.x, playerPos.y), cellsPerTile);

	// Still inside the resident tile. Tracked even when the load failed, so a missing tile is not
	// retried every frame.
	if (bnTileOriginValid && originCell.x == bnTileOriginCell.x && originCell.y == bnTileOriginCell.y)
		return;

	// Unload before loading so only one tile is ever resident.
	ReleaseBentNormalTileStream();

	bnTileOriginCell = originCell;
	bnTileOriginValid = true;

	auto path = TexGen::GetTilePath(cacheWorldspaceID, "_BN", (uint)tileSize, cellsPerTile, originCell);
	if (!std::filesystem::exists(path)) {
		logger::debug("[Skylighting] No bent normal tile for cell {}, {}", originCell.x, originCell.y);
		return;
	}

	if (!LoadCacheMap(path, &BNTileSRV)) {
		logger::error("[Skylighting] Failed to stream bent normal tile {}", path.string());
		return;
	}

	bnTileWorldBounds = float4(
		(float)originCell.x * TexGen::worldCellSize,
		(float)originCell.y * TexGen::worldCellSize,
		(float)(originCell.x + cellsPerTile) * TexGen::worldCellSize,
		(float)(originCell.y + cellsPerTile) * TexGen::worldCellSize);

	logger::debug("[Skylighting] Streamed bent normal tile at cell {}, {}", originCell.x, originCell.y);
}

#undef I18N_KEY_PREFIX
